### ISSUE TITLE
Isn't validate_parameters handled by the framework?

### ISSUE THREAD

**Issue by Trii** [moodlehq/moodle-local_wstemplate#3]
When debugging using a debugger, `self::validate_parameters` seems to be called before your function and that is how the parameters get passed into your function.
https://github.com/moodlehq/moodle-local_wstemplate/blob/master/externallib.php#L46

**Comment by dmonllao** [comment]
Hi @Trii, you might be interetested in https://tracker.moodle.org/browse/MDL-49355

**Comment by Trii** [comment]
That is good to know. Thanks!
