### ISSUE TITLE
Testing the custom web service.

### ISSUE THREAD

**Issue by pantelis90skatogithub1** [moodlehq/moodle-local_wstemplate#4]
Hello,

I am trying to implement a custom web service API with moodle in order to get data passed to a windows 8 application from moodle. I have searched a lot online and read many of Moodle's documentation with no success. I have tried their tutorials and what so ever but i have many difficulties implementing a custom web service. Fortunately i found your project.

I have downloaded and installed the web service on my localhost moodle 2.7. I have created a new token and added that in the client.php:
$token = 'blahblah';
$domainname = 'http://localhost/moodle';

I 've managed to install it with success but when i try to navigate to the link on my browser i get the following error:

<b>Notice</b>:  Undefined property: curl::$count in <b>E:\XAMPP\htdocs\moodle\local\wstemplate\client\curl.php</b> on line <b>179</b><br />
Array
(
    [faultCode] => 404
    [faultString] => Unknown error
)

which is :
private function formatHeader($ch, $header)
    {
        $this->count++;  //this line
        if (strlen($header) > 2) {
            list($key, $value) = explode(" ", rtrim($header, "\r\n"), 2);
            $key = rtrim($key, ':');
            if (!empty($this->response[$key])) {
                if (is_array($this->response[$key])){
                    $this->response[$key][] = $value;
                } else {
                    $tmp = $this->response[$key];
                    $this->response[$key] = array();
                    $this->response[$key][] = $tmp;
                    $this->response[$key][] = $value;

                }
            } else {
                $this->response[$key] = $value;
            }
        }
        return strlen($header);
    }

I searched for that error and i found another link "https://github.com/Conver/class.bitmessage.php/blob/master/curl.php" and it looks like that the property count is not set inside the curl.php in the current project. I tried adding the property but i still cannot run it.

Do you have any ideas? Am i missing anything?

Update from my previous message:
I have turned the developer's debug mode on and added the count in the curl.php as a property and the error now is:

Array
(
    [faultCode] => 28194976
    [faultString] => Method "local_wstemplate_hello_world" does not exist | ERRORCODE: 
)

there is nothing next to ERRORCODE:

Many thanks.
Pantelis G.

**Comment by mudrd8mz** [comment]
By quick looking I think the line 179 is just a mistake left-over during copy&pasting of the code. I believe it can be simply removed. The other error you are getting (`local_wstemplate_hello_world`) is sort of expected unless you actually have that web service function implemented on the server side.

I agree these examples should be polished out a bit. It is important to understand that they are not supposed to work as out-of-box tutorials themselves.

**Comment by pantelis90skatogithub1** [comment]
Hello,
Thank you for your answer. 
What do i have to do to implement a custom web service for my Moodle page? I thought that it would do the right thing because the web service (function) is written in the client.php in the wstemplate folder. What else do i have to do? And what if i need to write my custom sql queries in order to get some specific data from the server (because the Moodle web services are not suitable for my purpose)? Where do i write them?

The reason i am asking is because I need to pull some forms (and some other data) from the server to my windows 8 application. This Moodle server is running as a local independent entity in the university and only a few professors have access to it. I have managed to write a php script in order to get and send data to Moodle through ajax requests, but i placed the script in the the 'XAMPP\htdocs\moodle\course'. I construct a json file and send it through the api. It needs to be done right, the proper way. 

What is your suggestions for my questions?
Sorry for asking so many things. I just got curious by the functionalities of Moodle and i need some guidance to finish my project.

Many thanks.
Pantelis G.

**Comment by mudrd8mz** [comment]
It's quite complex, to be honest. I am unable to provide step-by-step support, but you generally want to look at how local plugins can be implemented in Moodle (https://docs.moodle.org/dev/Local_plugins) and how they can provide web service (https://docs.moodle.org/dev/Adding_a_web_service_to_a_plugin).

**Comment by pantelis90skatogithub1** [comment]
Thank you for your help. I hope i can work something out of these information.
Thanks again.
